# Generated by Django 2.2.1 on 2019-05-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_paper', models.CharField(default='', max_length=100)),
                ('conference_title', models.CharField(default='', max_length=100)),
                ('upload_paper', models.FileField(upload_to='')),
                ('proceeding_paper_title', models.CharField(default='', max_length=100)),
                ('author', models.CharField(default='', max_length=100)),
                ('speaker_name', models.CharField(default='', max_length=100)),
                ('other_authors', models.CharField(default='', max_length=100)),
                ('conference_location', models.CharField(default='', max_length=100)),
                ('sponsor', models.CharField(default='', max_length=100)),
                ('conference_start_date', models.DateField(default=1994)),
                ('conference_end_date', models.DateField(default=1994)),
                ('place_of_publication', models.CharField(blank=True, max_length=100)),
                ('online_link', models.URLField(default='')),
                ('latitude', models.CharField(default='', max_length=150)),
                ('longitude', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_of_agenda', models.IntegerField()),
                ('arrival_and_registraion', models.CharField(max_length=255)),
                ('induction_programme', models.CharField(max_length=255)),
                ('welcome_address', models.CharField(max_length=255)),
                ('induction_lectures', models.CharField(max_length=255)),
                ('induction_of_new_members', models.CharField(max_length=255)),
                ('welcome_address_by_president', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=200)),
                ('photograph', models.CharField(max_length=255)),
                ('documentary_on_cpn', models.CharField(max_length=255)),
                ('lunch', models.CharField(max_length=255)),
                ('annual_general_meeting', models.CharField(max_length=255)),
                ('dinner_and_presentation_of_awards_and_certificate', models.CharField(max_length=255)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='conference.Conference')),
            ],
            options={
                'ordering': ['order_of_agenda'],
                'unique_together': {('documentary_on_cpn', 'order_of_agenda')},
            },
        ),
    ]
