# Generated by Django 2.2.1 on 2019-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_downloads_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='File_Description',
            field=models.TextField(default='', max_length=200),
        ),
    ]
