# Generated by Django 2.2.1 on 2019-05-18 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Membership_Type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_registration_number', models.CharField(default='', max_length=150)),
                ('surname', models.CharField(default='', max_length=150)),
                ('First_name', models.CharField(default='', max_length=150)),
                ('Other_names', models.CharField(default='', max_length=150)),
                ('address', models.TextField(default='', max_length=200)),
                ('phone_number', models.IntegerField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('Payment_status', models.CharField(default='', max_length=50)),
                ('entry_types', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Member_Entry', to='attendees.TypeOfMembership')),
            ],
            options={
                'ordering': ['phone_number'],
                'unique_together': {('membership_registration_number', 'phone_number')},
            },
        ),
    ]
